---
- name: Include generated keys
  include_vars: "keys.yml"

- name: Include generated keys
  include_vars: "github.yml"

- ec2_remote_facts:
    filters:
      instance-state-name: running
      "tag:Name": "{{ vpc_sanctuary_instance_name }}"
    region: "{{ vpc_region }}"
  register: vaults

- name: Enable github auth backend
  shell: "VAULT_TOKEN={{ vault_token }} vault auth-enable --address={{ vpc_procotol }}://{{ vaults.instances[0].public_dns_name }}:8200 --tls-skip-verify github"

- name: Set organization
  shell: "VAULT_TOKEN={{ vault_token }} vault write --address={{ vpc_procotol }}://{{ vaults.instances[0].public_dns_name }}:8200 --tls-skip-verify auth/github/config organization={{ github_org }}"

- name: Give a team root permissions
  shell: "VAULT_TOKEN={{ vault_token }} vault write --address={{ vpc_procotol }}://{{ vaults.instances[0].public_dns_name }}:8200 --tls-skip-verify auth/github/map/teams/{{ github_team }} value=root"

