---
- name: Include generated keys
  include_vars: "keys.yml"

- name: Include github org and team names
  include_vars: "github.yml"


- name: Enable github auth backend
  shell: "VAULT_TOKEN={{ vault_token }} vault auth-enable --address={{ vpc_procotol }}://{{ sanctuary_hostname }}:{{ sanctuary_port }} {{ vault_cli_options }} github"

- name: Set organization
  shell: "VAULT_TOKEN={{ vault_token }} vault write --address={{ vpc_procotol }}://{{ sanctuary_hostname }}:{{ sanctuary_port }} {{ vault_cli_options }} auth/github/config organization={{ github_org }}"

- name: Give a team root permissions
  shell: "VAULT_TOKEN={{ vault_token }} vault write --address={{ vpc_procotol }}://{{ sanctuary_hostname }}:{{ sanctuary_port }} {{ vault_cli_options }} auth/github/map/teams/{{ github_team }} value=root"
