---
# tasks file for ansible.vault

- name: Updates apt cache
  apt: update_cache=true

- name: ensure prereqs exists
  apt: name={{ item }} state=present
  with_items:
   - unzip

- name: Download vault client
  get_url: >
    url="https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest=/tmp/vault.zip
    sha256sum={{ vault_sha256sum }}

- name: add vault binary to /usr/bin
  unarchive: src=/tmp/vault.zip dest=/usr/bin copy=no

- name: create vault config dir
  file: path=/etc/vault state=directory mode=0755

- name: copy run vault bash script
  template: src=templates/run_vault.sh.j2 dest=/usr/bin/run_vault.sh mode=0755

- name: copy upstart conf for vault
  copy: src=vault.conf dest=/etc/init/vault.conf mode=0644

- name: start vault service
  service: name=vault state=started
