---
# tasks file for ansible.vault

- name: Updates apt cache
  apt: update_cache=true

- name: ensure prereqs exists
  apt: name={{ item }} state=present
  with_items:
   - unzip

- name: Download vault client
  get_url: >
    url="https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest=/tmp/vault.zip
    sha256sum={{ vault_sha256sum }}

- name: add vault binary to /usr/bin
  unarchive: src=/tmp/vault.zip dest=/usr/bin copy=no

- name: download lets encrypt source
  get_url: >
    url="https://github.com/letsencrypt/letsencrypt/archive/v{{ letsencrypt_version }}.tar.gz"
    dest=/tmp/letsencrypt.tar.gz
    sha256sum={{ letsencrypt_sha256sum }}

- name: extract letsencrypt to /mtp
  unarchive: src=/tmp/letsencrypt.tar.gz dest=/tmp creates=yes copy=no

- name: stat letsencrypt dir
  stat: path="/tmp/letsencrypt-{{ letsencrypt_version }}"
  register: le_stat

- name: Move LE to /opt
  command: "mv /tmp/letsencrypt-{{ letsencrypt_version }} /opt/letsencrypt"
  when: le_stat.stat.exists

- name: create vault config dir
  file: path=/etc/vault state=directory mode=0755

- name: copy default certs into vault ami
  copy: src=/etc/certs dest=/etc/certs directory_mode=yes

- name: copy run vault bash script
  template: src=templates/run_vault.sh.j2 dest=/usr/bin/run_vault.sh mode=0755

- name: copy upstart conf for vault
  copy: src=vault.conf dest=/etc/init/vault.conf mode=0644
