---
# tasks file for ansible.vault

- name: Updates apt cache
  apt: update_cache=true

- name: ensure prereqs exists
  apt: name={{ item }} state=present
  with_items:
   - unzip

- name: Download vault client
  get_url: >
    url="https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest=/tmp/vault.zip
    sha256sum={{ vault_sha256sum }}

- name: add vault binary to /usr/bin
  unarchive: src=/tmp/vault.zip dest=/usr/bin copy=no

- name: download lets encrypt source
  get_url: >
    url="https://github.com/letsencrypt/letsencrypt/archive/v{{ letsencrypt_version }}.tar.gz"
    dest=/tmp/letsencrypt.tar.gz
    sha256sum={{ letsencrypt_sha256sum }}

- name: extract letsencrypt to /mtp
  unarchive: src=/tmp/letsencrypt.tar.gz dest=/tmp creates=yes copy=no

- name: stat letsencrypt dir
  stat: path="/tmp/letsencrypt-{{ letsencrypt_version }}"
  register: le_stat

- name: Move LE to /opt
  command: "mv /tmp/letsencrypt-{{ letsencrypt_version }} /opt/letsencrypt"
  when: le_stat.stat.exists

- name: create vault config dir
  file: path=/etc/vault state=directory mode=0755

- name: copy run vault bash script
  template: src=templates/run_vault.sh.j2 dest=/usr/bin/run_vault.sh mode=0755

- name: copy upstart conf for vault
  copy: src=vault.conf dest=/etc/init/vault.conf mode=0644

- name: This is the public IP of the Vault instance
  debug: var=groups['vaults'][0]
  when: le_domain != ''

- pause: prompt="Set your DNS to point to the ip listed above the press [ENTER]"
  when: le_domain != ''

- name: IF using LE wait for dns
  wait_for: host=letest.drud.us port=22 delay=10 state=started timeout=300
  when: le_domain != ''

- name: init LE
  command: "/opt/letsencrypt/letsencrypt-auto --staging --standalone --agree-tos --non-interactive -d {{ le_domain }} -m {{ le_email }} certonly"
  when: le_domain != ''

- name: start vault service
  service: name=vault state=started
