---
- name: Create IAM role
  iam:
    iam_type: user
    name: "{{ iam_user_name }}"
    state: present
    access_key_state: create
    key_count: 1
  register: iam_user

- name: Set the iam user key
  set_fact: iam_key="{{ iam_user.user_meta.access_keys[0] }}"

- name: Create IAM policy
  iam_policy:
    iam_type: user
    iam_name: "{{ iam_user_name }}"
    policy_name: "sanctuary_fullaccess_iam"
    state: present
    policy_json: "{{ lookup( 'template', 'dynamodb_policy.json.j2') }}"
