---
- name: Create IAM role
  iam:
    iam_type: role
    name: "{{ iam_role_name }}"
    state: present

- name: Create IAM policy
  iam_policy:
    iam_type: role
    iam_name: "{{ iam_role_name }}"
    policy_name: "sanctuary_fullaccess_iam"
    state: present
    policy_json: "{{ lookup( 'template', 'dynamodb_policy.json.j2') }}"

# If we move too quickly here the auto scaling group will complain that the role
# is not yet active. Slow things down a bit.
# @todo: proper wait-loop
- name: Pause to allow IAM role to propegate.
  pause: seconds=30
