---

- name: Ensure OpenSSL is installed
  apt: name=openssl state=present

- name: Check for server.crt
  local_action: stat path=/etc/certs/server.pem
  register: pem
  ignore_errors: True

- name: Ensure ssl folder exist
  file:
    path: "/etc/certs"
    state: directory

- include: usercerts.yml
  when: pem.stat.exists

- include: selfsigned.yml
  when: pem.stat.exists == False and le_domain == ''

- include: letsencrypt.yml
  when: pem.stat.exists == False and le_domain != ''
