---
  
- name: Ensure OpenSSL is installed
  apt: name=openssl state=present

- name: check for mounted in certs
  stat: path=/etc/certs/server.pem
  register: certfile

- name: Ensure ssl folder exist
  file:
    path: "/etc/certs"
    state: directory

- include: selfsigned.yml
  when: certfile.stat.exists == False and le_domain == ''

- include: letsencrypt.yml
  when: certfile.stat.exists == False and le_domain != ''
