- name: Check for server.crt
  local_action: stat path=/etc/certs/server.pem
  register: pem

- name: copy file if it exists
  copy: src=/etc/certs/server.pem dest=/etc/certs/server.pem
  when: pem.stat.exists


- name: Check for server.crt
  local_action: stat path=/etc/certs/server.crt
  register: crt

- name: copy file if it exists
  copy: src=/etc/certs/server.crt dest=/etc/certs/server.crt
  when: crt.stat.exists

- name: check for server.key
  local_action: stat path=/etc/certs/server.key
  register: key

- name: copy file if it exists
  copy: src=/etc/certs/server.key dest=/etc/certs/server.key
  when: key.stat.exists

- name: This is the public IP of the Vault instance
  debug: msg="{{ groups['vaults'][0] }}"

- pause: prompt="Set your DNS for {{ sanctuary_hostname }} to point to the ip listed above the press [ENTER]"
