---

- name: Initialize vault
  shell: "vault init --address={{ sanctuary_protocol }}://{{ sanctuary_hostname }}:{{ sanctuary_port }} --key-shares={{ vault_shares }} --key-threshold={{ vault_threshold }} {{ vault_cli_options }}"
  register: init
  ignore_errors: yes

- name: Write result
  local_action: copy content={{ init.stderr }} dest=/app/init.txt
  when: init|failed

- name: Write result
  local_action: copy content={{ init.stdout }} dest=/app/init.txt
  when: not init|failed
