---
- name: Find the latest Ubuntu AMI
  ec2_ami_search: "distro=ubuntu release=trusty region={{ vpc_region }}
store=ebs-ssd virt=hvm"
  register: ubuntu_image

- name: Launch sanctuary instance.
  ec2:
    region: "{{ vpc_region }}"
    key_name: "{{ vpc_key_name }}"
    instance_type: "{{ sanctuary_instance_size }}"
    image: "{{ ubuntu_image.ami }}"
    wait: yes
    group: "{{ vpc_sg_name }}"
    count: 1
    vpc_subnet_id: "{{ vpc.subnets[0].id }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ vpc_name }}-host"
  register: vaults

- name: Add new instance to host group
  add_host: hostname={{ item.public_ip }} groupname=vaults
  with_items: "{{ vaults.instances }}"

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: "{{ vaults.instances }}"
