---
# @todo: need to ensure this sorts by latest first.
- name: Look up sanctuary AMI.
  ec2_ami_find:
    owner: "{{ sanctuary_ami_owner }}"
    region: "{{ vpc_region }}"
    sort: name
    sort_order: descending
    ami_tags:
      Service: vault
    no_result_action: fail
  register: ami_find

- name: Launch sanctuary instance.
  ec2:
    region: "{{ vpc_region }}"
    key_name: "{{ vpc_key_name }}"
    instance_type: "{{ vpc_sanctuary_instance_size }}"
    image: "{{ ami_find.results[0].ami_id }}"
    wait: yes
    group: "{{ vpc_sg_name }}"
    count: 1
    instance_profile_name: "{{ iam_role_name }}"
    vpc_subnet_id: "{{ vpc.subnets[0].id }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ vpc_name }}-host"
