---
- ec2_remote_facts:
    filters:
      instance-state-name: running
      "tag:Name": "{{ sanctuary_instance_name }}"
    region: "{{ vpc_region }}"
  register: vaults

- name: Remove instances
  ec2:
    state: absent
    wait: yes
    region: "{{ vpc_region }}"
    instance_id: "{{ item.id }}"
  with_items: vaults.instances
