---
ssl_certs_country: "US"
ssl_certs_locality: "New York"
ssl_certs_organization: "Your company"
ssl_certs_state: "New York"
ssl_certs_common_name: "{{ansible_fqdn}}"
ssl_certs_days: "365"
ssl_certs_fields: "/C={{ssl_certs_country}}/ST={{ssl_certs_state}}/L={{ssl_certs_locality}}/O={{ssl_certs_organization}}/CN={{ssl_certs_common_name}}"

ssl_certs_path: "/etc/certs"
ssl_certs_privkey_path: "{{ssl_certs_path}}/server.key"
ssl_certs_cert_path: "{{ssl_certs_path}}/server.pem"
ssl_certs_csr_path: "{{ssl_certs_path}}/server.csr"
ssl_certs_mode: 700

