---
- name: Snapshot the running instance
  ec2_ami:
    instance_id: "{{ ami_instance.instances[0].id }}"
    wait: yes
    name: "{{ snapshot_ami_name }}"
    region: "{{ vpc_region }}"
    state: present
    tags:
      Name: sanctuary
      Service: vault
  register: ami
