---
- ec2_remote_facts:
    filters:
      instance-state-name: running
      "tag:Name": "{{ vpc_sanctuary_instance_name }}"
    region: "{{ vpc_region }}"
  register: vaults

- name: Wait for Vault port to come up
  wait_for: host={{ vaults.instances[0].public_dns_name }} port=8200 delay=60 timeout=320 state=started

- name: Initialize vault
  shell: "vault init --address=http://{{ vaults.instances[0].public_dns_name }}:8200"
  register: init
  ignore_errors: yes

- name: Write result
  local_action: copy content={{ init.stderr }} dest=/app/init.txt
  when: init|failed

- name: Write result
  local_action: copy content={{ init.stdout }} dest=/app/init.txt
  when: not init|failed
