---
- hosts: localhost
  tasks:
    - ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": "{{ vpc_sanctuary_instance_name }}"
        region: "{{ vpc_region }}"
      register: vaults

    - name: Include generated keys
      include_vars: "keys.yml"
      when: lookup('env', 'S3_AUDIT_BUCKET') != ''

    - name: Enable audit backend
      shell: "VAULT_TOKEN={{ vault_token }} vault audit-enable --address={{ vpc_procotol }}://{{ vaults.instances[0].public_dns_name }}:8200 -tls-skip-verify file path=/var/log/vault_audit.log"
      when: lookup('env', 'S3_AUDIT_BUCKET') != ''
