---
- hosts: localhost
  vars:
    - action: create
  roles:
    - iam
    - deploy_key
    - vpc
    - vault_hosts
  tags:
    - vpc

- hosts: vaults
  sudo: yes
  user: ubuntu
  vars:
    le_domain: "{{ lookup('env', 'LE_DOMAIN') }}"
    le_email: "{{ lookup('env', 'LE_EMAIL') }}"
  roles:
    - ssl-certs
    - vault
    - audit
  tags:
    - vaults
