---
- hosts: localhost
  vars:
    - action: create
  roles:
    - iam
    - deploy_key
    - vpc
    - vault_hosts
  tags:
    - vpc

- hosts: vaults
  sudo: yes
  user: ubuntu
  roles:
    - ssl-certs
    - vault
  tags:
    - vaults
