---

- name: Create VPC
  local_action:
    module: ec2_vpc
    region: "{{ vpc_region }}"
    cidr_block: "{{ vpc_ip_root }}.0.0/16"
    resource_tags: { "Name":"{{ vpc_name }}" }
    internet_gateway: True
    subnets:
        - cidr: "{{ vpc_ip_root }}.{{ az0_subnet_range}}/24"
          resource_tags: { "Name":"{{ vpc_name }}" }
          az: "{{ vpc_az0 }}"
    route_tables:
        - subnets:
            - "{{ vpc_ip_root }}.{{ az0_subnet_range}}/24"
          routes:
            - dest: 0.0.0.0/0
              gw: igw
  register: vpc

- name: Create a security group
  local_action:
    module: ec2_group
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    name: "{{ vpc_sg_name }}"
    description: "{{ vpc_sg_name }}"
    rules:
      - proto: icmp
        from_port: 8
        to_port: 0
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8200
        to_port: 8200
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: sanctuary_sg
